Import('*')

SimObject('ZIVReplacementPolicy.py', sim_objects=['ZIVReplacementPolicy'])

Source('ZIVReplacementPolicy.cc')
Source('SlotManager.cc')
Source('ROCQueue.cc')

DebugFlag('TDMOrder', "Ordering at TDM")
DebugFlag('XYZInfo', "Information")
DebugFlag('FlexLLC', "")
